[package]
name = "vizia"
version = "0.1.0"
edition = "2021"
license = "MIT"
description = "A Rust GUI Framework"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[example]]
name = "button"
path = "examples/controls/button.rs"


[[example]]
name = "slider"
path = "examples/controls/slider.rs"

[[example]]
name = "knob"
path = "examples/controls/knob.rs"

[[example]]
name = "checkbox"
path = "examples/controls/checkbox.rs"

[[example]]
name = "zstack"
path = "examples/controls/zstack.rs"

[features]
meadowlark = ["rusty-daw-core"]

[dependencies]
vizia_derive = {version = "0.1.0", path = "derive"}
femtovg = "0.2.5"
morphorm = {git = "https://github.com/geom3trik/morphorm", features = ["rounding"]}
# morphorm = {path = "../morphorm", features = ["rounding"]}
glutin = "0.28.0"
bitflags = "1.3.2"
keyboard-types = "0.6.1"
fluent-bundle = "0.15.2"
fluent-langneg = "0.13"
fluent-syntax = "0.11.0"
unic-langid = "0.9"
cssparser = "0.27.2"
raw-window-handle = "0.4.2"

rusty-daw-core = {version = "0.2", optional = true}

[dev-dependencies]
english-numbers = "0.3.3"