[package]
name = "vizia_core"
version = "0.1.0"
authors = ["George Atkinson"]
license = "MIT"
repository = "https://github.com/geom3trik/VIZIA"
edition = "2021"
description = "Core components of vizia"

[features]
meadowlark = ["rusty-daw-core"]

[dependencies]
vizia_derive = {version = "0.1.0", path = "../derive"}
femtovg = "0.2.8"
morphorm = {git = "https://github.com/geom3trik/morphorm", features = ["rounding"]}
# morphorm = {path = "../../morphorm", features = ["rounding"]}
bitflags = "1.3.2"
keyboard-types = { version = "0.5.0", default-features = false }
# fluent-bundle = "0.15.2"
# fluent-langneg = "0.13"
# fluent-syntax = "0.11.0"
unic-langid = "0.9"
cssparser = "0.27.2"
chumsky = "0.7.0"
ariadne = "0.1.3"

rusty-daw-core = {version = "0.7.4", optional = true}